steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  
  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: 'csc648-848-01-sw-engineering-summer-2023-T05/thrownAwayPrototype'

options: 
  logging: CLOUD_LOGGING_ONLY
